### ISSUE TITLE
Create a Breakathon Test Plan

### ISSUE THREAD

**Issue by swathiiyer2** [cs210/EdMod#26]
More information about Breakathon and the test plan here: https://github.com/cs210/Home/blob/master/Assignments/13-Breakathon/!-Breakathon.md

**Comment by jchuter** [comment]
https://docs.google.com/document/d/1pLWZBA99hKLZFDrVwGm3Dp2GVtq3PgMxmIueKM9T4xc/edit?usp=sharing
